
version: "3.8"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./snapshots:/app/snapshots
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - REDIS_BROKER=redis://redis:6379/0

  worker:
    build: .
    command: celery -A app.celery_worker worker --loglevel=info
    depends_on:
      - backend
      - redis
    volumes:
      - ./snapshots:/app/snapshots
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - REDIS_BROKER=redis://redis:6379/0

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
